language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - if [[ $TRAVIS_PHP_VERSION = '5.3' ]]; then
  -   wget https://pecl.php.net/get/libevent-0.1.0.tgz
  -   tar zxvfp libevent-0.1.0.tgz
  -   cd libevent-0.1.0
  -   phpize
  -   ./configure
  -   make
  -   make install
  -   echo "extension = libevent.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - elif [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then
  -   git clone https://bitbucket.org/osmanov/pecl-event.git
  -   cd pecl-event
  -   phpize
  -   ./configure --with-event-core --with-event-extra --enable-event-debug
  -   make
  -   make install
  -   echo "extension = event.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - fi
  - cd ..
  - composer install
  - cd tests

script: phpunit -v
